version: '3.8'

services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vision-ai-web-dev
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - vision-ai-network
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.js:/app/vite.config.js
      # Don't mount node_modules
      - /app/node_modules
    environment:
      - NODE_ENV=development

networks:
  vision-ai-network:
    driver: bridge 